@hostname = http://localhost:3000

### GET all tours
GET {{hostname}}/api/v1/tours?page=5&limit=10

### GET Top 5 tours
GET {{hostname}}/api/v1/tours/top-5-cheap

### GET specific tour
GET {{hostname}}/api/v1/tours/69b9c18fe4be8683c5007208

### GET tour stats
GET {{hostname}}/api/v1/tours/tour-stats

### GET monthly plans
GET {{hostname}}/api/v1/tours/monthly-plan/2021

### CREATE tour
POST {{hostname}}/api/v1/tours
Content-Type: application/json

{
    "name": "The Snow Adventurer",
    "duration": 4,
    "maxGroupSize": 10,
    "difficulty": "difficult",
    "ratingsAverage": 4.5,
    "ratingsQuantity": 13,
    "price": 997,
    "summary": "Exciting adventure in the snow with snowboarding and skiing",
    "description": "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua, ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum!\nDolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, exercitation ullamco laboris nisi ut aliquip. Lorem ipsum dolor sit amet, consectetur adipisicing elit!",
    "imageCover": "tour-3-cover.jpg",
    "images": [
      "tour-3-1.jpg",
      "tour-3-2.jpg",
      "tour-3-3.jpg"
    ],
    "startDates": [
      "2022-01-05,10:00",
      "2022-02-12,10:00",
      "2023-01-06,10:00"
    ]
  }

### Update tour
PATCH {{hostname}}/api/v1/tours/69b84bf7d74ed03a0c4bff46
Content-Type: application/json

{
  "price": 500
}

### Delete tour
DELETE  {{hostname}}/api/v1/tours/69b9b94c3056adf1de01e088

### GET all users
GET {{hostname}}/api/v1/users/

### GET user
GET {{hostname}}/api/v1/users/1

### Create User
POST {{hostname}}/api/v1/users

### Update user
PATCH {{hostname}}/api/v1/users/1

### Delete user
DELETE {{hostname}}/api/v1/users/1