@hostname = http://localhost:3000

### GET all tours
GET {{hostname}}/api/v1/tours

### GET Top 5 tours
GET {{hostname}}/api/v1/tours/top-5-cheap

### GET specific tour
GET {{hostname}}/api/v1/tours/wwww

### GET tour stats
GET {{hostname}}/api/v1/tours/tour-stats

### GET monthly plans
GET {{hostname}}/api/v1/tours/monthly-plan/2021

### CREATE tour
POST {{hostname}}/api/v1/tours
Content-Type: application/json

{
  "name": "The Snow Adventurer",
  "duration": 4,
  "secret": false,
  "maxGroupSize": 10,
"priceDiscount": 100,
  "difficulty": "easy",
  "price": 997,
  "summary": "Testing the tour",
  "imageCover": "tour-3-cover.jpg",
  "ratingsAverage": 4
}

### Update tour
PATCH {{hostname}}/api/v1/tours/69b84bf7d74ed03a0c4bff46
Content-Type: application/json

{
  "price": 500
}

### Delete tour
DELETE  {{hostname}}/api/v1/tours/69bad40961875d9d5b440fc1

### GET all users
GET {{hostname}}/api/v1/users/

### GET user
GET {{hostname}}/api/v1/users/1

### Create User
POST {{hostname}}/api/v1/users

### Update user
PATCH {{hostname}}/api/v1/users/1

### Delete user
DELETE {{hostname}}/api/v1/users/1